### ISSUE TITLE
Rush dates on homepage

### ISSUE THREAD

**Issue by epan2so** [ThetaTauMiami/thetataumiami.github.io#13]
Update the homepage with upcoming info/rush times.

**Comment by epan2so** [comment]
Rush dates should be visible on homepage without having to scroll down.
You could include them in the caption of the slideshow (which should also be updated with new pictures).

The fancy line looks nice but I think it would make more sense on a different page.

**Comment by Vutisat** [comment]
Yes commander!

On Tue, Feb 9, 2016 at 8:33 AM, Emily Pantuso <notifications@github.com>
wrote:

> Rush dates should be visible on homepage without having to scroll down.
> You could include them in the caption of the slideshow (which should also
> be updated with new pictures).
>
> The fancy line looks nice but I think it would make more sense on a
> different page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThetaTauMiami/thetataumiami.github.io/issues/13#issuecomment-181866605>
> .
>



-- 

*Pob (Thiti) Vutisalchavakul*

Miami University | Class of 2016

College of Engineering and Computing | Computer Science

LOCKHEED MARTIN LEADERSHIP INSTITUTE
<http://eas.miamioh.edu/fileadmin/leadership-institute/brochure/index2.html>

Theta Tau | Petition Director, Marketing Chair (Former)

(937) 846-6809 | Vutisat@MiamiOH.edu
